"""Script to generate 05_feature_engineering.ipynb for Day 8."""
import json
import sys

sys.stdout.reconfigure(encoding="utf-8")


def code_cell(cell_id, source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cell_id,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }


def md_cell(cell_id, source_lines):
    return {
        "cell_type": "markdown",
        "id": cell_id,
        "metadata": {},
        "source": source_lines,
    }


cells = []

# ── f000m: Title
cells.append(md_cell("f000m", [
    "# Day 8 — Feature Engineering & Re-tuning\n",
    "\n",
    "Continues from `04_tuning.ipynb` (Day 7).  \n",
    "Goals:\n",
    "- **Task 3 (delay_category):** re-tune with 2 new interaction features (`util_x_queue`, `util_x_tight`). Target: G3 weighted_f1 > 0.725.\n",
    "- **Task 4 (delay_root_cause):** consolidate rare classes → 6-class target, re-tune. Target: G4 macro_f1 > 0.50.\n",
    "\n",
    "Tasks 1 and 2 are not re-tuned (G1 and G2 already passed in Day 7).",
]))

# ── f001: Imports
cells.append(code_cell("f001", [
    "import os\n",
    "import tempfile\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import mlflow\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "from sklearn.metrics import classification_report\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "import sys\n",
    "sys.path.insert(0, str(Path(\"../src\").resolve()))\n",
    "\n",
    "from mpc_ml.features.constants import (\n",
    "    DELAY_CATEGORY_ORDER,\n",
    "    ROOT_CAUSE_CLASSES,\n",
    "    TARGET_COLS,\n",
    "    INTERACTION_FEATURE_NAMES,\n",
    ")\n",
    "from mpc_ml.features.pipeline import build_pipeline, get_feature_names\n",
    "from mpc_ml.models.tuning import (\n",
    "    build_optuna_objective,\n",
    "    run_study,\n",
    "    best_params_to_model,\n",
    ")\n",
    "from mpc_ml.models.evaluation import evaluate_model\n",
    "from mpc_ml.tracking.mlflow_utils import (\n",
    "    get_experiment_name,\n",
    "    log_model_with_signature,\n",
    "    log_standard_params,\n",
    "    log_standard_metrics,\n",
    "    log_standard_artifacts,\n",
    "    start_run,\n",
    ")\n",
    "\n",
    "warnings.filterwarnings(\"ignore\", category=UserWarning)\n",
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
    "\n",
    "print(\"Imports OK\")\n",
    "print(f\"Interaction features ({len(INTERACTION_FEATURE_NAMES)}): {INTERACTION_FEATURE_NAMES}\")",
]))

# ── f002: Constants
cells.append(code_cell("f002", [
    "_NOTEBOOK_DIR = Path(os.getcwd())\n",
    "PROJECT_ROOT  = _NOTEBOOK_DIR.parent.parent\n",
    "MLFLOW_URI    = (PROJECT_ROOT / \"mlruns\").resolve().as_uri()\n",
    "mlflow.set_tracking_uri(MLFLOW_URI)\n",
    "\n",
    "PHASE        = \"day8\"\n",
    "N_TRIALS     = 100\n",
    "N_CV_SPLITS  = 5\n",
    "RANDOM_STATE = 42\n",
    "\n",
    "# Day 8 gate targets (unchanged from Day 7)\n",
    "G3_THRESHOLD = 0.725   # delay_category weighted_f1\n",
    "G4_THRESHOLD = 0.50    # root_cause macro_f1 (6-class)\n",
    "\n",
    "# Task 4 class consolidation\n",
    "# machine_breakdown (21 train) + quality_failure_rework (23 train)\n",
    "#   -> equipment_process_failure (44 train — learnable)\n",
    "RC_CONSOLIDATE_MAP = {\n",
    "    \"machine_breakdown\":      \"equipment_process_failure\",\n",
    "    \"quality_failure_rework\": \"equipment_process_failure\",\n",
    "}\n",
    "# 6-class ordered list (5 original remaining + 1 consolidated)\n",
    "RC_CLASSES_6 = tuple(\n",
    "    c for c in ROOT_CAUSE_CLASSES\n",
    "    if c not in (\"machine_breakdown\", \"quality_failure_rework\")\n",
    ") + (\"equipment_process_failure\",)\n",
    "\n",
    "print(f\"MLflow URI:  {MLFLOW_URI}\")\n",
    "print(f\"N_TRIALS:    {N_TRIALS}  |  N_CV_SPLITS: {N_CV_SPLITS}\")\n",
    "print(f\"Day 8 targets: G3>{G3_THRESHOLD}  G4>{G4_THRESHOLD} (6-class)\")\n",
    "print(f\"RC_CLASSES_6 ({len(RC_CLASSES_6)}): {RC_CLASSES_6}\")",
]))

# ── f003: Data loading
cells.append(code_cell("f003", [
    "DATA_DIR = Path(\"../data/processed\")\n",
    "train_df = pd.read_csv(DATA_DIR / \"train.csv\")\n",
    "val_df   = pd.read_csv(DATA_DIR / \"val.csv\")\n",
    "\n",
    "# Raw feature DataFrames (37 cols; pipeline adds 6 interaction features -> 43 total)\n",
    "X_train = train_df.drop(columns=[c for c in TARGET_COLS if c in train_df.columns])\n",
    "X_val   = val_df.drop(columns=[c for c in TARGET_COLS if c in val_df.columns])\n",
    "\n",
    "# Task 3 labels\n",
    "y_train_cat = train_df[\"delay_category\"]\n",
    "y_val_cat   = val_df[\"delay_category\"]\n",
    "\n",
    "# Task 4: delayed-only filter (same as Day 7)\n",
    "train_d = train_df[train_df[\"is_delayed\"] == 1].copy()\n",
    "val_d   = val_df[val_df[\"is_delayed\"] == 1].copy()\n",
    "X_train_d    = train_d.drop(columns=[c for c in TARGET_COLS if c in train_d.columns])\n",
    "X_val_d      = val_d.drop(columns=[c for c in TARGET_COLS if c in val_d.columns])\n",
    "y_train_rc_d = train_d[\"delay_root_cause\"]\n",
    "y_val_rc_d   = val_d[\"delay_root_cause\"]\n",
    "\n",
    "# Task 4 (6-class): apply consolidation map\n",
    "y_train_rc_6 = y_train_rc_d.replace(RC_CONSOLIDATE_MAP)\n",
    "y_val_rc_6   = y_val_rc_d.replace(RC_CONSOLIDATE_MAP)\n",
    "\n",
    "# scale_pos_weight (binary; unused for multiclass)\n",
    "n_neg = (train_df[\"is_delayed\"] == 0).sum()\n",
    "n_pos = (train_df[\"is_delayed\"] == 1).sum()\n",
    "scale_pos_weight = n_neg / n_pos\n",
    "\n",
    "print(f\"train: {len(train_df):,} rows  |  val: {len(val_df):,} rows\")\n",
    "print(f\"Task 3 classes: {sorted(y_train_cat.unique())}\")\n",
    "print(f\"Task 4 delayed train: {len(train_d):,}  |  val: {len(val_d):,}\")\n",
    "print(f\"\\nTask 4 7-class (train):\\n{y_train_rc_d.value_counts().to_string()}\")\n",
    "print(f\"\\nTask 4 6-class after consolidation (train):\\n{y_train_rc_6.value_counts().to_string()}\")\n",
    "print(f\"\\nTask 4 6-class (val):\\n{y_val_rc_6.value_counts().to_string()}\")",
]))

# ── f004: Feature verification
cells.append(code_cell("f004", [
    "# Verify new interaction features are present and non-trivial before tuning\n",
    "probe_pipe = build_pipeline()\n",
    "probe_pipe.fit(X_train)\n",
    "X_probe = probe_pipe.transform(X_train)\n",
    "\n",
    "print(f\"Pipeline output shape: {X_probe.shape}  (expected: ({len(X_train)}, 43))\")\n",
    "assert X_probe.shape[1] == 43, f\"Expected 43 features, got {X_probe.shape[1]}\"\n",
    "\n",
    "for feat in [\"util_x_queue\", \"util_x_tight\"]:\n",
    "    assert feat in X_probe.columns, f\"{feat} missing from pipeline output\"\n",
    "    std_val = X_probe[feat].std()\n",
    "    assert std_val > 0.01, f\"{feat} has near-zero std={std_val:.4f}\"\n",
    "    print(f\"  {feat}: mean={X_probe[feat].mean():.4f}  std={std_val:.4f}  (StandardScaled)\")\n",
    "\n",
    "print(\"\\nAll 43 features verified. Pipeline ready for Day 8 tuning.\")\n",
    "del probe_pipe, X_probe",
]))

# ── f005m: Task 3 header
cells.append(md_cell("f005m", [
    "## Task 3 — Delay Category Re-tuning\n",
    "\n",
    "Re-tunes with the augmented feature set (43 features including `util_x_queue` and `util_x_tight`).  \n",
    "Day 7 best val weighted_f1 = 0.6976. Target: > 0.725.  \n",
    "Empirical baseline with Day 7 params + new features (no re-tune): 0.7077.",
]))

# ── f006: Task 3 Optuna
cells.append(code_cell("f006", [
    "print(\"Task 3 — Building Optuna objective (LightGBM, delay_category, 43 features)\\n\")\n",
    "cat_objective = build_optuna_objective(\n",
    "    X_train, y_train_cat,\n",
    "    model_type=\"lightgbm\",\n",
    "    task=\"delay_category\",\n",
    "    n_splits=N_CV_SPLITS,\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "cat_study = run_study(\n",
    "    cat_objective,\n",
    "    n_trials=N_TRIALS,\n",
    "    study_name=\"category_lightgbm_day8\",\n",
    "    seed=RANDOM_STATE,\n",
    ")\n",
    "print(f\"Best CV weighted_f1: {cat_study.best_value:.4f}  (Day 7 best: 0.7130)\")\n",
    "print(f\"Best trial: #{cat_study.best_trial.number}\")\n",
    "print(f\"Best params: {cat_study.best_params}\")",
]))

# ── f007: Task 3 Final training
cells.append(code_cell("f007", [
    "print(\"Task 3 — Final training with best params\\n\")\n",
    "cat_estimator = best_params_to_model(\n",
    "    cat_study,\n",
    "    model_type=\"lightgbm\",\n",
    "    task=\"delay_category\",\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "cat_pipeline = Pipeline([\n",
    "    (\"preprocessor\", build_pipeline()),\n",
    "    (\"model\", cat_estimator),\n",
    "])\n",
    "cat_pipeline.fit(X_train, y_train_cat)\n",
    "\n",
    "cat_preprocessor = cat_pipeline.named_steps[\"preprocessor\"]\n",
    "cat_model        = cat_pipeline.named_steps[\"model\"]\n",
    "\n",
    "cat_val_metrics = evaluate_model(cat_model, cat_preprocessor, X_val, y_val_cat, \"delay_category\")\n",
    "cat_weighted_f1 = cat_val_metrics[\"val_weighted_f1\"]\n",
    "cat_macro_f1    = cat_val_metrics[\"val_macro_f1\"]\n",
    "\n",
    "X_val_t_cat   = cat_preprocessor.transform(X_val)\n",
    "X_train_t_cat = cat_preprocessor.transform(X_train)\n",
    "\n",
    "print(f\"val_weighted_f1: {cat_weighted_f1:.4f}  (Day 7: 0.6976  |  target: >{G3_THRESHOLD})\")\n",
    "print(f\"val_macro_f1:    {cat_macro_f1:.4f}\")\n",
    "\n",
    "y_pred_cat = cat_model.predict(X_val_t_cat)\n",
    "cr_cat = classification_report(\n",
    "    y_val_cat, y_pred_cat,\n",
    "    labels=list(DELAY_CATEGORY_ORDER), zero_division=0,\n",
    ")\n",
    "print(f\"\\nTask 3 Day 8 classification report:\")\n",
    "print(cr_cat)",
]))

# ── f008: Task 3 MLflow logging
cells.append(code_cell("f008", [
    "print(f\"Task 3 — Logging to: {get_experiment_name('delay_category')}\\n\")\n",
    "cat_all_metrics = {\n",
    "    **cat_val_metrics,\n",
    "    \"optuna_best_cv_weighted_f1\": round(cat_study.best_value, 6),\n",
    "}\n",
    "safe_params = {k: v for k, v in cat_study.best_params.items()\n",
    "               if isinstance(v, (str, int, float, bool))}\n",
    "safe_params[\"model_name\"]   = \"lightgbm\"\n",
    "safe_params[\"task\"]         = \"delay_category\"\n",
    "safe_params[\"num_classes\"]  = len(DELAY_CATEGORY_ORDER)\n",
    "safe_params[\"n_features\"]   = X_train_t_cat.shape[1]\n",
    "safe_params[\"phase\"]        = PHASE\n",
    "safe_params[\"new_features\"] = \"util_x_queue,util_x_tight\"\n",
    "\n",
    "cm_cat_path = Path(tempfile.gettempdir()) / \"cm_cat_day8.png\"\n",
    "from mpc_ml.models.evaluation import confusion_matrix_annotated\n",
    "cm_cat_df = confusion_matrix_annotated(cat_model, X_val_t_cat, y_val_cat)\n",
    "n_cls = len(DELAY_CATEGORY_ORDER)\n",
    "fig, ax = plt.subplots(figsize=(7, 5))\n",
    "sns.heatmap(\n",
    "    cm_cat_df.iloc[:, :n_cls].astype(float), annot=True, fmt=\".0f\", cmap=\"Blues\",\n",
    "    ax=ax, cbar=False,\n",
    "    xticklabels=list(DELAY_CATEGORY_ORDER),\n",
    "    yticklabels=list(DELAY_CATEGORY_ORDER),\n",
    ")\n",
    "ax.set_title(\"Task 3 LightGBM Day 8 — delay_category\")\n",
    "ax.set_xlabel(\"Predicted\"); ax.set_ylabel(\"True\")\n",
    "plt.xticks(rotation=30, ha=\"right\"); fig.tight_layout()\n",
    "fig.savefig(cm_cat_path, dpi=100); plt.close(fig)\n",
    "\n",
    "day8_run_ids = {}\n",
    "tags = {\"model_type\": \"lightgbm\", \"task\": \"delay_category\", \"phase\": PHASE, \"is_champion\": \"True\"}\n",
    "with start_run(get_experiment_name(\"delay_category\"), f\"lightgbm_{PHASE}\", tags=tags) as run:\n",
    "    log_standard_params(safe_params)\n",
    "    log_standard_metrics(cat_all_metrics)\n",
    "    log_model_with_signature(\n",
    "        cat_pipeline, X_train, X_train_t_cat,\n",
    "        registered_model_name=\"delay_category_classifier\",\n",
    "    )\n",
    "    log_standard_artifacts(\n",
    "        classification_report=cr_cat,\n",
    "        confusion_matrix_path=cm_cat_path,\n",
    "    )\n",
    "    day8_run_ids[\"category\"] = run.info.run_id\n",
    "cm_cat_path.unlink(missing_ok=True)\n",
    "print(f\"  run_id={day8_run_ids['category']}  weighted_f1={cat_weighted_f1:.4f}\")",
]))

# ── f009: Gate G3
cells.append(code_cell("f009", [
    "# Gate G3 — Day 8: delay_category weighted_f1 > 0.725\n",
    "# If this assert fails: do NOT proceed to Task 4.\n",
    "# Next action: implement historical delay duration feature (Phase B3 backup plan).\n",
    "assert cat_weighted_f1 > G3_THRESHOLD, (\n",
    "    f\"GATE G3 FAILED: delay_category val_weighted_f1={cat_weighted_f1:.4f} <= {G3_THRESHOLD}.\\n\"\n",
    "    f\"Optuna best CV={cat_study.best_value:.4f}. Day 7 val was 0.6976. \"\n",
    "    \"Interaction features improved but G3 not reached. \"\n",
    "    \"Action required: implement historical delay duration feature (Phase B3).\"\n",
    ")\n",
    "print(f\"GATE G3 PASSED: delay_category val_weighted_f1={cat_weighted_f1:.4f}  (Day 8 target >{G3_THRESHOLD})\")",
]))

# ── f010m: Task 4 header
cells.append(md_cell("f010m", [
    "## Task 4 — Root Cause (6-class consolidation)\n",
    "\n",
    "`machine_breakdown` (21 train, 8 val) + `quality_failure_rework` (23 train, 5 val) merged into `equipment_process_failure`.  \n",
    "Combined: 44 train samples — above learnable threshold.  \n",
    "Day 7 7-class macro_f1 = 0.4213. Target (6-class): > 0.50.",
]))

# ── f011: Task 4 Optuna (6-class)
cells.append(code_cell("f011", [
    "print(\"Task 4 — Building Optuna objective (LightGBM, delay_root_cause, 6-class)\\n\")\n",
    "print(f\"6-class distribution (train):\\n{y_train_rc_6.value_counts().to_string()}\\n\")\n",
    "\n",
    "rc_objective = build_optuna_objective(\n",
    "    X_train_d, y_train_rc_6,\n",
    "    model_type=\"lightgbm\",\n",
    "    task=\"delay_root_cause\",\n",
    "    n_splits=N_CV_SPLITS,\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "rc_study = run_study(\n",
    "    rc_objective,\n",
    "    n_trials=N_TRIALS,\n",
    "    study_name=\"root_cause_lightgbm_day8_6class\",\n",
    "    seed=RANDOM_STATE,\n",
    ")\n",
    "print(f\"Best CV macro_f1: {rc_study.best_value:.4f}  (Day 7 7-class: 0.4842)\")\n",
    "print(f\"Best trial: #{rc_study.best_trial.number}\")\n",
    "print(f\"Best params: {rc_study.best_params}\")",
]))

# ── f012: Task 4 Final training
cells.append(code_cell("f012", [
    "print(\"Task 4 — Final training with best params (6-class)\\n\")\n",
    "rc_estimator = best_params_to_model(\n",
    "    rc_study,\n",
    "    model_type=\"lightgbm\",\n",
    "    task=\"delay_root_cause\",\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "rc_pipeline = Pipeline([\n",
    "    (\"preprocessor\", build_pipeline()),\n",
    "    (\"model\", rc_estimator),\n",
    "])\n",
    "# LightGBM handles string labels natively\n",
    "rc_pipeline.fit(X_train_d, y_train_rc_6)\n",
    "\n",
    "rc_preprocessor = rc_pipeline.named_steps[\"preprocessor\"]\n",
    "rc_model        = rc_pipeline.named_steps[\"model\"]\n",
    "\n",
    "rc_val_metrics = evaluate_model(rc_model, rc_preprocessor, X_val_d, y_val_rc_6, \"delay_root_cause\")\n",
    "rc_macro_f1    = rc_val_metrics[\"val_macro_f1\"]\n",
    "rc_weighted_f1 = rc_val_metrics[\"val_weighted_f1\"]\n",
    "\n",
    "X_val_d_t_rc   = rc_preprocessor.transform(X_val_d)\n",
    "X_train_d_t_rc = rc_preprocessor.transform(X_train_d)\n",
    "\n",
    "print(f\"val_macro_f1:    {rc_macro_f1:.4f}  (Day 7 7-class: 0.4213  |  target 6-class: >{G4_THRESHOLD})\")\n",
    "print(f\"val_weighted_f1: {rc_weighted_f1:.4f}\")\n",
    "\n",
    "y_pred_rc = rc_model.predict(X_val_d_t_rc)\n",
    "cr_rc = classification_report(\n",
    "    y_val_rc_6, y_pred_rc,\n",
    "    labels=list(RC_CLASSES_6), zero_division=0,\n",
    ")\n",
    "print(f\"\\nTask 4 Day 8 classification report (6-class):\")\n",
    "print(cr_rc)",
]))

# ── f013: Task 4 MLflow logging
cells.append(code_cell("f013", [
    "print(f\"Task 4 — Logging to: {get_experiment_name('delay_root_cause')}\\n\")\n",
    "rc_all_metrics = {\n",
    "    **rc_val_metrics,\n",
    "    \"optuna_best_cv_macro_f1\":    round(rc_study.best_value, 6),\n",
    "    \"num_classes_consolidated\":   6,\n",
    "}\n",
    "safe_params = {k: v for k, v in rc_study.best_params.items()\n",
    "               if isinstance(v, (str, int, float, bool))}\n",
    "safe_params[\"model_name\"]          = \"lightgbm\"\n",
    "safe_params[\"task\"]                = \"delay_root_cause\"\n",
    "safe_params[\"num_classes\"]         = 6\n",
    "safe_params[\"training_filter\"]     = \"is_delayed=1\"\n",
    "safe_params[\"class_consolidation\"] = \"machine_breakdown+quality_failure_rework->equipment_process_failure\"\n",
    "safe_params[\"n_features\"]          = X_train_d_t_rc.shape[1]\n",
    "safe_params[\"phase\"]               = PHASE\n",
    "\n",
    "cm_rc_path = Path(tempfile.gettempdir()) / \"cm_rc_day8.png\"\n",
    "from mpc_ml.models.evaluation import confusion_matrix_annotated\n",
    "cm_rc_df = confusion_matrix_annotated(rc_model, X_val_d_t_rc, y_val_rc_6)\n",
    "n_cls_rc = len(RC_CLASSES_6)\n",
    "fig, ax = plt.subplots(figsize=(9, 6))\n",
    "sns.heatmap(\n",
    "    cm_rc_df.iloc[:, :n_cls_rc].astype(float), annot=True, fmt=\".0f\", cmap=\"Blues\",\n",
    "    ax=ax, cbar=False,\n",
    "    xticklabels=list(RC_CLASSES_6),\n",
    "    yticklabels=list(RC_CLASSES_6),\n",
    ")\n",
    "ax.set_title(\"Task 4 LightGBM Day 8 — delay_root_cause (6-class)\")\n",
    "ax.set_xlabel(\"Predicted\"); ax.set_ylabel(\"True\")\n",
    "plt.xticks(rotation=35, ha=\"right\"); fig.tight_layout()\n",
    "fig.savefig(cm_rc_path, dpi=100); plt.close(fig)\n",
    "\n",
    "tags = {\n",
    "    \"model_type\": \"lightgbm\", \"task\": \"delay_root_cause\",\n",
    "    \"phase\": PHASE, \"is_champion\": \"True\", \"class_consolidation\": \"6class\",\n",
    "}\n",
    "with start_run(get_experiment_name(\"delay_root_cause\"), f\"lightgbm_{PHASE}_6class\", tags=tags) as run:\n",
    "    log_standard_params(safe_params)\n",
    "    log_standard_metrics(rc_all_metrics)\n",
    "    log_model_with_signature(\n",
    "        rc_pipeline, X_train_d, X_train_d_t_rc,\n",
    "        registered_model_name=\"root_cause_classifier\",\n",
    "    )\n",
    "    log_standard_artifacts(\n",
    "        classification_report=cr_rc,\n",
    "        confusion_matrix_path=cm_rc_path,\n",
    "    )\n",
    "    day8_run_ids[\"root_cause\"] = run.info.run_id\n",
    "cm_rc_path.unlink(missing_ok=True)\n",
    "print(f\"  run_id={day8_run_ids['root_cause']}  macro_f1={rc_macro_f1:.4f}\")",
]))

# ── f014: Gate G4
cells.append(code_cell("f014", [
    "# Gate G4 — Day 8: root_cause macro_f1 > 0.50 (6-class)\n",
    "assert rc_macro_f1 > G4_THRESHOLD, (\n",
    "    f\"GATE G4 FAILED: root_cause val_macro_f1={rc_macro_f1:.4f} <= {G4_THRESHOLD} (6-class).\\n\"\n",
    "    f\"Optuna best CV={rc_study.best_value:.4f}. \"\n",
    "    \"Class consolidation insufficient. Consider SMOTE or additional feature engineering.\"\n",
    ")\n",
    "print(f\"GATE G4 PASSED: root_cause val_macro_f1={rc_macro_f1:.4f}  (Day 8 target >{G4_THRESHOLD}, 6-class)\")",
]))

# ── f015m: Summary header
cells.append(md_cell("f015m", ["## Day 8 Gate Summary"]))

# ── f016: Final gate summary
cells.append(code_cell("f016", [
    "print(\"=\" * 64)\n",
    "print(\"DAY 8 GATE CHECK\")\n",
    "print(\"=\" * 64)\n",
    "\n",
    "gates = {\n",
    "    \"G1 binary AUC >= 0.909 (Day 7 PASS \\u2014 not re-tuned)\": True,\n",
    "    \"G2 regression R\\u00b2 > 0.22 (Day 7 PASS \\u2014 not re-tuned)\": True,\n",
    "    f\"G3 delay_category weighted_f1 > {G3_THRESHOLD}\": cat_weighted_f1 > G3_THRESHOLD,\n",
    "    f\"G4 root_cause macro_f1 > {G4_THRESHOLD} (6-class)\": rc_macro_f1 > G4_THRESHOLD,\n",
    "    \"G5 MLflow run_ids non-null\": all(v and v != \"N/A\" for v in day8_run_ids.values()),\n",
    "    \"G6 test.csv never loaded\": True,\n",
    "}\n",
    "values = {\n",
    "    \"G1 binary AUC >= 0.909 (Day 7 PASS \\u2014 not re-tuned)\": \"0.9100 (Day 7)\",\n",
    "    \"G2 regression R\\u00b2 > 0.22 (Day 7 PASS \\u2014 not re-tuned)\": \"0.2445 (Day 7)\",\n",
    "    f\"G3 delay_category weighted_f1 > {G3_THRESHOLD}\": f\"{cat_weighted_f1:.4f}\",\n",
    "    f\"G4 root_cause macro_f1 > {G4_THRESHOLD} (6-class)\": f\"{rc_macro_f1:.4f}\",\n",
    "    \"G5 MLflow run_ids non-null\": f\"{len(day8_run_ids)} runs\",\n",
    "    \"G6 test.csv never loaded\": \"confirmed\",\n",
    "}\n",
    "\n",
    "all_pass = True\n",
    "for gate, passed in gates.items():\n",
    "    status = \"\\u2713 PASS\" if passed else \"\\u2717 FAIL\"\n",
    "    print(f\"  {status}  {gate:<58}  actual={values[gate]}\")\n",
    "    if not passed:\n",
    "        all_pass = False\n",
    "\n",
    "print()\n",
    "if all_pass:\n",
    "    print(\"Day 8 COMPLETE \\u2014 all gates passed.\")\n",
    "    print(\"Proceed to 06_shap_analysis.ipynb for explainability.\")\n",
    "else:\n",
    "    print(\"Day 8 INCOMPLETE \\u2014 one or more gates failed.\")\n",
    "\n",
    "print(f\"\\nMLflow URI: {MLFLOW_URI}\")\n",
    "print(\"Day 8 runs logged:\")\n",
    "for t, rid in day8_run_ids.items():\n",
    "    print(f\"  {t:<20} run_id={rid}\")",
]))

# ── Assemble notebook
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.12.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

out = "d:/Kuliah/Project/manufacturing-factory-simulation/manufacturing-process-copilot/ml/notebooks/05_feature_engineering.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written {out}")
print(f"Total cells: {len(cells)}")
print(f"Code cells: {sum(1 for c in cells if c['cell_type'] == 'code')}")
