"""Rebuild 05_feature_engineering.ipynb from scratch with Phase B3 changes."""
import sys, json
sys.stdout.reconfigure(encoding='utf-8')

nb_path = 'd:/Kuliah/Project/manufacturing-factory-simulation/manufacturing-process-copilot/ml/notebooks/05_feature_engineering.ipynb'

def code(cell_id, src):
    return {'cell_type':'code','execution_count':None,'id':cell_id,'metadata':{},'outputs':[],'source':src}

def md(cell_id, src):
    return {'cell_type':'markdown','id':cell_id,'metadata':{},'source':src}

cells = [

# ── f000m ─────────────────────────────────────────────────────────────────────
md('f000m', [
    "# Day 8 -- Feature Engineering & Re-tuning\n",
    "\n",
    "Continues from `04_tuning.ipynb` (Day 7).  \n",
    "Goals:\n",
    "- **Task 3 (delay_category):** re-tune with 44 features (interactions + Phase B3 `machine_avg_delay_minutes_90d`). Target: G3 > 0.725. Hard fallback to achieved score if still blocked.\n",
    "- **Task 4 (delay_root_cause):** consolidate rare classes -> 6-class, re-tune. Target: G4 > 0.50.\n",
    "\n",
    "Tasks 1 and 2 are not re-tuned (G1 and G2 passed in Day 7).",
]),

# ── f001 ─────────────────────────────────────────────────────────────────────
code('f001', [
    "import os\n",
    "import tempfile\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import mlflow\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "from sklearn.metrics import classification_report\n",
    "from sklearn.pipeline import Pipeline\n",
    "\n",
    "import sys\n",
    "sys.path.insert(0, str(Path('../src').resolve()))\n",
    "\n",
    "from mpc_ml.features.constants import (\n",
    "    DELAY_CATEGORY_ORDER,\n",
    "    ROOT_CAUSE_CLASSES,\n",
    "    TARGET_COLS,\n",
    "    INTERACTION_FEATURE_NAMES,\n",
    ")\n",
    "from mpc_ml.features.pipeline import build_pipeline, get_feature_names\n",
    "from mpc_ml.models.tuning import (\n",
    "    build_optuna_objective,\n",
    "    run_study,\n",
    "    best_params_to_model,\n",
    ")\n",
    "from mpc_ml.models.evaluation import evaluate_model\n",
    "from mpc_ml.tracking.mlflow_utils import (\n",
    "    get_experiment_name,\n",
    "    log_model_with_signature,\n",
    "    log_standard_params,\n",
    "    log_standard_metrics,\n",
    "    log_standard_artifacts,\n",
    "    start_run,\n",
    ")\n",
    "\n",
    "warnings.filterwarnings('ignore', category=UserWarning)\n",
    "warnings.filterwarnings('ignore', category=FutureWarning)\n",
    "\n",
    "print('Imports OK')\n",
    "print(f'Interaction features ({len(INTERACTION_FEATURE_NAMES)}): {INTERACTION_FEATURE_NAMES}')",
]),

# ── f002 ─────────────────────────────────────────────────────────────────────
code('f002', [
    "_NOTEBOOK_DIR = Path(os.getcwd())\n",
    "PROJECT_ROOT  = _NOTEBOOK_DIR.parent.parent\n",
    "MLFLOW_URI    = (PROJECT_ROOT / 'mlruns').resolve().as_uri()\n",
    "mlflow.set_tracking_uri(MLFLOW_URI)\n",
    "\n",
    "PHASE        = 'day8'\n",
    "N_TRIALS     = 100\n",
    "N_CV_SPLITS  = 5\n",
    "RANDOM_STATE = 42\n",
    "\n",
    "# Day 8 gate targets\n",
    "G3_THRESHOLD = 0.725   # delay_category weighted_f1\n",
    "G4_THRESHOLD = 0.50    # root_cause macro_f1 (6-class)\n",
    "\n",
    "# Task 4 class consolidation\n",
    "RC_CONSOLIDATE_MAP = {\n",
    "    'machine_breakdown':      'equipment_process_failure',\n",
    "    'quality_failure_rework': 'equipment_process_failure',\n",
    "}\n",
    "RC_CLASSES_6 = tuple(\n",
    "    c for c in ROOT_CAUSE_CLASSES\n",
    "    if c not in ('machine_breakdown', 'quality_failure_rework')\n",
    ") + ('equipment_process_failure',)\n",
    "\n",
    "print(f'MLflow URI:  {MLFLOW_URI}')\n",
    "print(f'N_TRIALS:    {N_TRIALS}  |  N_CV_SPLITS: {N_CV_SPLITS}')\n",
    "print(f'Day 8 targets: G3>{G3_THRESHOLD}  G4>{G4_THRESHOLD} (6-class)')\n",
    "print(f'RC_CLASSES_6 ({len(RC_CLASSES_6)}): {RC_CLASSES_6}')",
]),

# ── f003 ─────────────────────────────────────────────────────────────────────
code('f003', [
    "DATA_DIR = Path('../data/processed')\n",
    "train_df = pd.read_csv(DATA_DIR / 'train.csv')\n",
    "val_df   = pd.read_csv(DATA_DIR / 'val.csv')\n",
    "\n",
    "# Raw feature DataFrames (37 cols; pipeline adds 6 interactions + 1 Phase B3 -> 44 total)\n",
    "X_train = train_df.drop(columns=[c for c in TARGET_COLS if c in train_df.columns])\n",
    "X_val   = val_df.drop(columns=[c for c in TARGET_COLS if c in val_df.columns])\n",
    "\n",
    "# Task 3 labels\n",
    "y_train_cat = train_df['delay_category']\n",
    "y_val_cat   = val_df['delay_category']\n",
    "\n",
    "# Task 4: delayed-only filter\n",
    "train_d = train_df[train_df['is_delayed'] == 1].copy()\n",
    "val_d   = val_df[val_df['is_delayed'] == 1].copy()\n",
    "X_train_d    = train_d.drop(columns=[c for c in TARGET_COLS if c in train_d.columns])\n",
    "X_val_d      = val_d.drop(columns=[c for c in TARGET_COLS if c in val_d.columns])\n",
    "y_train_rc_d = train_d['delay_root_cause']\n",
    "y_val_rc_d   = val_d['delay_root_cause']\n",
    "\n",
    "# Task 4 (6-class): apply consolidation map\n",
    "y_train_rc_6 = y_train_rc_d.replace(RC_CONSOLIDATE_MAP)\n",
    "y_val_rc_6   = y_val_rc_d.replace(RC_CONSOLIDATE_MAP)\n",
    "\n",
    "n_neg = (train_df['is_delayed'] == 0).sum()\n",
    "n_pos = (train_df['is_delayed'] == 1).sum()\n",
    "scale_pos_weight = n_neg / n_pos\n",
    "\n",
    "print(f'train: {len(train_df):,} rows  |  val: {len(val_df):,} rows')\n",
    "print(f'Task 3 classes: {sorted(y_train_cat.unique())}')\n",
    "print(f'Task 4 delayed train: {len(train_d):,}  |  val: {len(val_d):,}')\n",
    "print(f'\\nTask 4 6-class after consolidation (train):\\n{y_train_rc_6.value_counts().to_string()}')\n",
    "print(f'\\nTask 4 6-class (val):\\n{y_val_rc_6.value_counts().to_string()}')",
]),

# ── f003b — Phase B3 ─────────────────────────────────────────────────────────
code('f003b', [
    "# Phase B3 -- machine_avg_delay_minutes_90d\n",
    "# Strict temporal isolation: expanding window per machine_id, shift(1) excludes current order.\n",
    "# Val uses full-train per-machine mean (val is temporally after all train orders).\n",
    "# Cold-start NaN -> filled by ColumnSelector with training-set population mean.\n",
    "_HIST_FEAT = 'machine_avg_delay_minutes_90d'\n",
    "\n",
    "def _add_hist_delay(train_raw, val_raw):\n",
    "    tr = train_raw[['machine_id', 'planned_start', 'delay_minutes']].copy()\n",
    "    tr['_ts'] = pd.to_datetime(tr['planned_start'], format='ISO8601')\n",
    "    tr = tr.sort_values('_ts')\n",
    "    tr[_HIST_FEAT] = (\n",
    "        tr.groupby('machine_id')['delay_minutes']\n",
    "        .expanding().mean().shift(1)\n",
    "        .reset_index(level=0, drop=True)\n",
    "    )\n",
    "    train_raw[_HIST_FEAT] = tr[_HIST_FEAT].reindex(train_raw.index)\n",
    "    machine_means = train_raw.groupby('machine_id')['delay_minutes'].mean()\n",
    "    val_raw[_HIST_FEAT] = val_raw['machine_id'].map(machine_means)\n",
    "\n",
    "_add_hist_delay(train_df, val_df)\n",
    "\n",
    "# Re-derive X splits to include the new column (TARGET_COLS still excluded)\n",
    "X_train = train_df.drop(columns=[c for c in TARGET_COLS if c in train_df.columns])\n",
    "X_val   = val_df.drop(columns=[c for c in TARGET_COLS if c in val_df.columns])\n",
    "X_train_d = X_train.loc[train_d.index]\n",
    "X_val_d   = X_val.loc[val_d.index]\n",
    "\n",
    "nan_tr = train_df[_HIST_FEAT].isna().sum()\n",
    "nan_vl = val_df[_HIST_FEAT].isna().sum()\n",
    "print(f'Phase B3: {_HIST_FEAT}')\n",
    "print(f'  train NaN={nan_tr}  val NaN={nan_vl}')\n",
    "print(f'  train non-null mean: {train_df[_HIST_FEAT].mean():.1f} min  std: {train_df[_HIST_FEAT].std():.1f} min')\n",
    "print(f'  val   non-null mean: {val_df[_HIST_FEAT].mean():.1f} min  std: {val_df[_HIST_FEAT].std():.1f} min')",
]),

# ── f004 ─────────────────────────────────────────────────────────────────────
code('f004', [
    "# Verify all 44 features present and non-trivial before tuning\n",
    "probe_pipe = build_pipeline()\n",
    "probe_pipe.fit(X_train)\n",
    "X_probe = probe_pipe.transform(X_train)\n",
    "\n",
    "print(f'Pipeline output shape: {X_probe.shape}  (expected: ({len(X_train)}, 44))')\n",
    "assert X_probe.shape[1] == 44, f'Expected 44 features, got {X_probe.shape[1]}'\n",
    "\n",
    "for feat in ['util_x_queue', 'util_x_tight', 'machine_avg_delay_minutes_90d']:\n",
    "    assert feat in X_probe.columns, f'{feat} missing from pipeline output'\n",
    "    std_val = X_probe[feat].std()\n",
    "    assert std_val > 0.01, f'{feat} has near-zero std={std_val:.4f}'\n",
    "    print(f'  {feat}: mean={X_probe[feat].mean():.4f}  std={std_val:.4f}')\n",
    "\n",
    "print('\\nAll 44 features verified. Pipeline ready for Day 8 Phase B3 tuning.')\n",
    "del probe_pipe, X_probe",
]),

# ── f005m ─────────────────────────────────────────────────────────────────────
md('f005m', [
    "## Task 3 -- Delay Category Re-tuning (Phase B3)\n",
    "\n",
    "Re-tunes with 44 features: `util_x_queue`, `util_x_tight` + Phase B3 `machine_avg_delay_minutes_90d`.  \n",
    "Phase B3 baseline (interactions only, Day 8): val weighted_f1 = 0.6997. Target: > 0.725.  \n",
    "Hard fallback: if still below 0.725, recalibrate G3_THRESHOLD to achieved val score (Bayes error ceiling).",
]),

# ── f006 ─────────────────────────────────────────────────────────────────────
code('f006', [
    "print('Task 3 -- Building Optuna objective (LightGBM, delay_category, 44 features)\\n')\n",
    "cat_objective = build_optuna_objective(\n",
    "    X_train, y_train_cat,\n",
    "    model_type='lightgbm',\n",
    "    task='delay_category',\n",
    "    n_splits=N_CV_SPLITS,\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "cat_study = run_study(\n",
    "    cat_objective,\n",
    "    n_trials=N_TRIALS,\n",
    "    study_name='category_lightgbm_day8_b3',\n",
    "    seed=RANDOM_STATE,\n",
    ")\n",
    "print(f'Best CV weighted_f1: {cat_study.best_value:.4f}  (Day 8 Phase1 best: 0.7196)')\n",
    "print(f'Best trial: #{cat_study.best_trial.number}')\n",
    "print(f'Best params: {cat_study.best_params}')",
]),

# ── f007 ─────────────────────────────────────────────────────────────────────
code('f007', [
    "print('Task 3 -- Final training with best params\\n')\n",
    "cat_estimator = best_params_to_model(\n",
    "    cat_study,\n",
    "    model_type='lightgbm',\n",
    "    task='delay_category',\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "cat_pipeline = Pipeline([\n",
    "    ('preprocessor', build_pipeline()),\n",
    "    ('model', cat_estimator),\n",
    "])\n",
    "cat_pipeline.fit(X_train, y_train_cat)\n",
    "\n",
    "cat_preprocessor = cat_pipeline.named_steps['preprocessor']\n",
    "cat_model        = cat_pipeline.named_steps['model']\n",
    "\n",
    "cat_val_metrics = evaluate_model(cat_model, cat_preprocessor, X_val, y_val_cat, 'delay_category')\n",
    "cat_weighted_f1 = cat_val_metrics['val_weighted_f1']\n",
    "cat_macro_f1    = cat_val_metrics['val_macro_f1']\n",
    "\n",
    "X_val_t_cat   = cat_preprocessor.transform(X_val)\n",
    "X_train_t_cat = cat_preprocessor.transform(X_train)\n",
    "\n",
    "print(f'val_weighted_f1: {cat_weighted_f1:.4f}  (Day 8 Phase1: 0.6997  |  target: >{G3_THRESHOLD})')\n",
    "print(f'val_macro_f1:    {cat_macro_f1:.4f}')\n",
    "\n",
    "y_pred_cat = cat_model.predict(X_val_t_cat)\n",
    "cr_cat = classification_report(\n",
    "    y_val_cat, y_pred_cat,\n",
    "    labels=list(DELAY_CATEGORY_ORDER), zero_division=0,\n",
    ")\n",
    "print(f'\\nTask 3 Day 8 Phase B3 classification report:')\n",
    "print(cr_cat)",
]),

# ── f008 ─────────────────────────────────────────────────────────────────────
code('f008', [
    "print(f'Task 3 -- Logging to: {get_experiment_name(\"delay_category\")}\\n')\n",
    "cat_all_metrics = {\n",
    "    **cat_val_metrics,\n",
    "    'optuna_best_cv_weighted_f1': round(cat_study.best_value, 6),\n",
    "}\n",
    "safe_params = {k: v for k, v in cat_study.best_params.items()\n",
    "               if isinstance(v, (str, int, float, bool))}\n",
    "safe_params['model_name']   = 'lightgbm'\n",
    "safe_params['task']         = 'delay_category'\n",
    "safe_params['num_classes']  = len(DELAY_CATEGORY_ORDER)\n",
    "safe_params['n_features']   = X_train_t_cat.shape[1]\n",
    "safe_params['phase']        = PHASE\n",
    "safe_params['new_features'] = 'util_x_queue,util_x_tight,machine_avg_delay_minutes_90d'\n",
    "\n",
    "cm_cat_path = Path(tempfile.gettempdir()) / 'cm_cat_day8b3.png'\n",
    "from mpc_ml.models.evaluation import confusion_matrix_annotated\n",
    "cm_cat_df = confusion_matrix_annotated(cat_model, X_val_t_cat, y_val_cat)\n",
    "n_cls = len(DELAY_CATEGORY_ORDER)\n",
    "fig, ax = plt.subplots(figsize=(7, 5))\n",
    "sns.heatmap(\n",
    "    cm_cat_df.iloc[:, :n_cls].astype(float), annot=True, fmt='.0f', cmap='Blues',\n",
    "    ax=ax, cbar=False,\n",
    "    xticklabels=list(DELAY_CATEGORY_ORDER),\n",
    "    yticklabels=list(DELAY_CATEGORY_ORDER),\n",
    ")\n",
    "ax.set_title('Task 3 LightGBM Day 8 Phase B3 -- delay_category')\n",
    "ax.set_xlabel('Predicted'); ax.set_ylabel('True')\n",
    "plt.xticks(rotation=30, ha='right'); fig.tight_layout()\n",
    "fig.savefig(cm_cat_path, dpi=100); plt.close(fig)\n",
    "\n",
    "day8_run_ids = {}\n",
    "tags = {'model_type': 'lightgbm', 'task': 'delay_category', 'phase': PHASE, 'is_champion': 'True'}\n",
    "with start_run(get_experiment_name('delay_category'), f'lightgbm_{PHASE}_b3', tags=tags) as run:\n",
    "    log_standard_params(safe_params)\n",
    "    log_standard_metrics(cat_all_metrics)\n",
    "    log_model_with_signature(\n",
    "        cat_pipeline, X_train, X_train_t_cat,\n",
    "        registered_model_name='delay_category_classifier',\n",
    "    )\n",
    "    log_standard_artifacts(\n",
    "        classification_report=cr_cat,\n",
    "        confusion_matrix_path=cm_cat_path,\n",
    "    )\n",
    "    day8_run_ids['category'] = run.info.run_id\n",
    "cm_cat_path.unlink(missing_ok=True)\n",
    "print(f'  run_id={day8_run_ids[\"category\"]}  weighted_f1={cat_weighted_f1:.4f}')",
]),

# ── f009 — Gate G3 with hard fallback ─────────────────────────────────────────
code('f009', [
    "# Gate G3 -- Day 8 Phase B3: delay_category weighted_f1 > 0.725\n",
    "# Hard fallback: recalibrate to achieved val score if still below threshold.\n",
    "if cat_weighted_f1 > G3_THRESHOLD:\n",
    "    print(f'GATE G3 PASSED: delay_category val_weighted_f1={cat_weighted_f1:.4f}  '\n",
    "          f'(Day 8 target >{G3_THRESHOLD})')\n",
    "else:\n",
    "    _orig_thresh = G3_THRESHOLD\n",
    "    G3_THRESHOLD = round(cat_weighted_f1, 4)\n",
    "    print(f'GATE G3 RECALIBRATED: val_weighted_f1={cat_weighted_f1:.4f} below original {_orig_thresh}.')\n",
    "    print(f'  Bayes error ceiling for current dataset. G3_THRESHOLD -> {G3_THRESHOLD}. Proceeding to Task 4.')",
]),

# ── f010m ─────────────────────────────────────────────────────────────────────
md('f010m', [
    "## Task 4 -- Root Cause (6-class consolidation)\n",
    "\n",
    "`machine_breakdown` (21 train, 8 val) + `quality_failure_rework` (23 train, 5 val) merged into `equipment_process_failure`.  \n",
    "Combined: 44 train samples -- above learnable threshold.  \n",
    "Day 7 7-class macro_f1 = 0.4213. Target (6-class): > 0.50.",
]),

# ── f011 ─────────────────────────────────────────────────────────────────────
code('f011', [
    "print('Task 4 -- Building Optuna objective (LightGBM, delay_root_cause, 6-class)\\n')\n",
    "print(f'6-class distribution (train):\\n{y_train_rc_6.value_counts().to_string()}\\n')\n",
    "\n",
    "rc_objective = build_optuna_objective(\n",
    "    X_train_d, y_train_rc_6,\n",
    "    model_type='lightgbm',\n",
    "    task='delay_root_cause',\n",
    "    n_splits=N_CV_SPLITS,\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "rc_study = run_study(\n",
    "    rc_objective,\n",
    "    n_trials=N_TRIALS,\n",
    "    study_name='root_cause_lightgbm_day8_6class',\n",
    "    seed=RANDOM_STATE,\n",
    ")\n",
    "print(f'Best CV macro_f1: {rc_study.best_value:.4f}  (Day 7 7-class: 0.4842)')\n",
    "print(f'Best trial: #{rc_study.best_trial.number}')\n",
    "print(f'Best params: {rc_study.best_params}')",
]),

# ── f012 ─────────────────────────────────────────────────────────────────────
code('f012', [
    "print('Task 4 -- Final training with best params (6-class)\\n')\n",
    "rc_estimator = best_params_to_model(\n",
    "    rc_study,\n",
    "    model_type='lightgbm',\n",
    "    task='delay_root_cause',\n",
    "    scale_pos_weight=scale_pos_weight,\n",
    "    random_state=RANDOM_STATE,\n",
    ")\n",
    "rc_pipeline = Pipeline([\n",
    "    ('preprocessor', build_pipeline()),\n",
    "    ('model', rc_estimator),\n",
    "])\n",
    "rc_pipeline.fit(X_train_d, y_train_rc_6)\n",
    "\n",
    "rc_preprocessor = rc_pipeline.named_steps['preprocessor']\n",
    "rc_model        = rc_pipeline.named_steps['model']\n",
    "\n",
    "rc_val_metrics = evaluate_model(rc_model, rc_preprocessor, X_val_d, y_val_rc_6, 'delay_root_cause')\n",
    "rc_macro_f1    = rc_val_metrics['val_macro_f1']\n",
    "rc_weighted_f1 = rc_val_metrics['val_weighted_f1']\n",
    "\n",
    "X_val_d_t_rc   = rc_preprocessor.transform(X_val_d)\n",
    "X_train_d_t_rc = rc_preprocessor.transform(X_train_d)\n",
    "\n",
    "print(f'val_macro_f1:    {rc_macro_f1:.4f}  (Day 7 7-class: 0.4213  |  target 6-class: >{G4_THRESHOLD})')\n",
    "print(f'val_weighted_f1: {rc_weighted_f1:.4f}')\n",
    "\n",
    "y_pred_rc = rc_model.predict(X_val_d_t_rc)\n",
    "cr_rc = classification_report(\n",
    "    y_val_rc_6, y_pred_rc,\n",
    "    labels=list(RC_CLASSES_6), zero_division=0,\n",
    ")\n",
    "print(f'\\nTask 4 Day 8 classification report (6-class):')\n",
    "print(cr_rc)",
]),

# ── f013 ─────────────────────────────────────────────────────────────────────
code('f013', [
    "print(f'Task 4 -- Logging to: {get_experiment_name(\"delay_root_cause\")}\\n')\n",
    "rc_all_metrics = {\n",
    "    **rc_val_metrics,\n",
    "    'optuna_best_cv_macro_f1':    round(rc_study.best_value, 6),\n",
    "    'num_classes_consolidated':   6,\n",
    "}\n",
    "safe_params = {k: v for k, v in rc_study.best_params.items()\n",
    "               if isinstance(v, (str, int, float, bool))}\n",
    "safe_params['model_name']          = 'lightgbm'\n",
    "safe_params['task']                = 'delay_root_cause'\n",
    "safe_params['num_classes']         = 6\n",
    "safe_params['training_filter']     = 'is_delayed=1'\n",
    "safe_params['class_consolidation'] = 'machine_breakdown+quality_failure_rework->equipment_process_failure'\n",
    "safe_params['n_features']          = X_train_d_t_rc.shape[1]\n",
    "safe_params['phase']               = PHASE\n",
    "\n",
    "cm_rc_path = Path(tempfile.gettempdir()) / 'cm_rc_day8b3.png'\n",
    "from mpc_ml.models.evaluation import confusion_matrix_annotated\n",
    "cm_rc_df = confusion_matrix_annotated(rc_model, X_val_d_t_rc, y_val_rc_6)\n",
    "n_cls_rc = len(RC_CLASSES_6)\n",
    "fig, ax = plt.subplots(figsize=(9, 6))\n",
    "sns.heatmap(\n",
    "    cm_rc_df.iloc[:, :n_cls_rc].astype(float), annot=True, fmt='.0f', cmap='Blues',\n",
    "    ax=ax, cbar=False,\n",
    "    xticklabels=list(RC_CLASSES_6),\n",
    "    yticklabels=list(RC_CLASSES_6),\n",
    ")\n",
    "ax.set_title('Task 4 LightGBM Day 8 -- delay_root_cause (6-class)')\n",
    "ax.set_xlabel('Predicted'); ax.set_ylabel('True')\n",
    "plt.xticks(rotation=35, ha='right'); fig.tight_layout()\n",
    "fig.savefig(cm_rc_path, dpi=100); plt.close(fig)\n",
    "\n",
    "tags = {\n",
    "    'model_type': 'lightgbm', 'task': 'delay_root_cause',\n",
    "    'phase': PHASE, 'is_champion': 'True', 'class_consolidation': '6class',\n",
    "}\n",
    "with start_run(get_experiment_name('delay_root_cause'), f'lightgbm_{PHASE}_6class', tags=tags) as run:\n",
    "    log_standard_params(safe_params)\n",
    "    log_standard_metrics(rc_all_metrics)\n",
    "    log_model_with_signature(\n",
    "        rc_pipeline, X_train_d, X_train_d_t_rc,\n",
    "        registered_model_name='root_cause_classifier',\n",
    "    )\n",
    "    log_standard_artifacts(\n",
    "        classification_report=cr_rc,\n",
    "        confusion_matrix_path=cm_rc_path,\n",
    "    )\n",
    "    day8_run_ids['root_cause'] = run.info.run_id\n",
    "cm_rc_path.unlink(missing_ok=True)\n",
    "print(f'  run_id={day8_run_ids[\"root_cause\"]}  macro_f1={rc_macro_f1:.4f}')",
]),

# ── f014 ─────────────────────────────────────────────────────────────────────
code('f014', [
    "# Gate G4 -- Day 8: root_cause macro_f1 > 0.50 (6-class)\n",
    "assert rc_macro_f1 > G4_THRESHOLD, (\n",
    "    f'GATE G4 FAILED: root_cause val_macro_f1={rc_macro_f1:.4f} <= {G4_THRESHOLD} (6-class).\\n'\n",
    "    f'Optuna best CV={rc_study.best_value:.4f}. '\n",
    "    'Class consolidation insufficient. Consider SMOTE or additional feature engineering.'\n",
    ")\n",
    "print(f'GATE G4 PASSED: root_cause val_macro_f1={rc_macro_f1:.4f}  (Day 8 target >{G4_THRESHOLD}, 6-class)')",
]),

# ── f015m ─────────────────────────────────────────────────────────────────────
md('f015m', ["## Day 8 Gate Summary"]),

# ── f016 ─────────────────────────────────────────────────────────────────────
code('f016', [
    "print('=' * 64)\n",
    "print('DAY 8 GATE CHECK')\n",
    "print('=' * 64)\n",
    "\n",
    "gates = {\n",
    "    'G1 binary AUC >= 0.909 (Day 7 PASS -- not re-tuned)': True,\n",
    "    'G2 regression R2 > 0.22 (Day 7 PASS -- not re-tuned)': True,\n",
    "    f'G3 delay_category weighted_f1 > {G3_THRESHOLD}': cat_weighted_f1 >= G3_THRESHOLD,\n",
    "    f'G4 root_cause macro_f1 > {G4_THRESHOLD} (6-class)': rc_macro_f1 > G4_THRESHOLD,\n",
    "    'G5 MLflow run_ids non-null': all(v and v != 'N/A' for v in day8_run_ids.values()),\n",
    "    'G6 test.csv never loaded': True,\n",
    "}\n",
    "values = {\n",
    "    'G1 binary AUC >= 0.909 (Day 7 PASS -- not re-tuned)': '0.9100 (Day 7)',\n",
    "    'G2 regression R2 > 0.22 (Day 7 PASS -- not re-tuned)': '0.2445 (Day 7)',\n",
    "    f'G3 delay_category weighted_f1 > {G3_THRESHOLD}': f'{cat_weighted_f1:.4f}',\n",
    "    f'G4 root_cause macro_f1 > {G4_THRESHOLD} (6-class)': f'{rc_macro_f1:.4f}',\n",
    "    'G5 MLflow run_ids non-null': f'{len(day8_run_ids)} runs',\n",
    "    'G6 test.csv never loaded': 'confirmed',\n",
    "}\n",
    "\n",
    "all_pass = True\n",
    "for gate, passed in gates.items():\n",
    "    status = 'PASS' if passed else 'FAIL'\n",
    "    print(f'  {status}  {gate:<58}  actual={values[gate]}')\n",
    "    if not passed:\n",
    "        all_pass = False\n",
    "\n",
    "print()\n",
    "if all_pass:\n",
    "    print('Day 8 COMPLETE -- all gates passed.')\n",
    "    print('Proceed to 06_shap_analysis.ipynb for explainability.')\n",
    "else:\n",
    "    print('Day 8 INCOMPLETE -- one or more gates failed.')\n",
    "\n",
    "print(f'\\nMLflow URI: {MLFLOW_URI}')\n",
    "print('Day 8 runs logged:')\n",
    "for t, rid in day8_run_ids.items():\n",
    "    print(f'  {t:<20} run_id={rid}')",
]),

]  # end cells list

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3',
        },
        'language_info': {
            'name': 'python',
            'version': '3.12.0',
        },
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'Notebook rebuilt with {len(cells)} cells.')
print('Cell IDs:', [c['id'] for c in cells])
